web1:
  before_deploy:
  # Download media images from github repo & extract
  - "tar -xz < <(curl -s http://quickstart-downloads.gopagoda.io/magento-media.tar.gz)"
  # Import sample catalog sql file
  - "php pagoda/magento_sample_data.php"
  - "mysql -h $DB1_HOST --port $DB1_PORT -u $DB1_USER -p$DB1_PASS $DB1_NAME < /tmp/magento_sample_data_processed.sql"
  - "php index.php > /dev/null"
  # Increase php execution time to accomidate db import & migrations
  php_max_execution_time: 300
